/**
 * Heal Wounds — the fourth step of the Advancement Phase (pg. 19).
 *
 * ## Equally, which is an algorithm rather than a division
 *
 * A facility's Health points are shared **equally** among the survivors
 * assigned to healing: nobody takes a second point until everyone who can use
 * one has had a first. Dividing the pool by the head count gets this wrong the
 * moment anybody fills up — max HP is the survivor's Tier, and a survivor who
 * reaches it drops out and leaves the remainder to the others.
 *
 * So `sharedEqually` hands out one point at a time, in roster order, round
 * after round. Two things follow, and both are asserted as properties rather
 * than as examples: nobody ever exceeds their maximum, and between any two
 * survivors who are still taking points the allocations differ by at most one.
 *
 * ## Points first, Health second
 *
 * `sharedEqually` decides **who gets how many points**; `withWoundsHealed`
 * turns points into Health. They are two functions because the book will later
 * make them two decisions: a point spent on Infection instead of on a wound is
 * Phase 7 (pg. 30), and it is the same point from the same pool. Fusing the
 * distribution into the healing would mean taking them apart again.
 *
 * ## Rest is a different rule arriving at the same survivors
 *
 * A resting survivor generates one Health that **only they** may use (pg. 19,
 * 21). It never enters the shared pool, which is why it is a second function
 * rather than a survivor added to the first.
 *
 * Pure, like the rest of `src/engine`.
 */

import { REST_HEALTH, type HealthSource } from '../data/turn';
import { staffOf, survivorsDoing } from './assignments';
import { occupants } from './base';
import type { Campaign, Survivor } from './campaign';
import type { Check, Violation } from './checks';
import { facilityProduction } from './production';
import { maxHp } from './survivor';

export type HealingViolationCode = 'health-going-spare' | 'nothing-to-share';

export type HealingViolation = Violation<HealingViolationCode>;

export type HealingCheck = Check<HealingViolationCode>;

/** One survivor's share of a turn's Health, and where it came from. */
export interface HealthAward {
  readonly survivor: string;
  readonly health: number;
  /** Shared out of a facility's pool, or generated by resting (pg. 19, 21). */
  readonly source: HealthSource;
}

/**
 * How much Health this survivor can still take.
 *
 * Never negative. A survivor above their maximum is a state the app can hold —
 * Health is typed in, and Z1-7's override lets a roster break the rules on
 * purpose — and "minus two rooms" is not a number any distribution should try
 * to reason about. No room is the honest answer.
 */
export function room(survivor: Survivor): number {
  return Math.max(0, maxHp(survivor) - survivor.currentHp);
}

/**
 * The Health the base's facilities make this turn (pg. 19, 69).
 *
 * Through `facilityProduction` and `staffOf`, so this and the number on the
 * slot card are the same computation summed differently — a Medical Clinic's
 * output is its staff's combined Medicine Score, halved for want of Water.
 */
export function healingPool(campaign: Campaign): number {
  const base = campaign.base;
  if (base === null) return 0;

  let total = 0;

  for (const occupant of occupants(base)) {
    for (const line of facilityProduction(occupant, staffOf(campaign, occupant.slotId))) {
      if (line.outputs.includes('health')) total += line.amount;
    }
  }

  return total;
}

/** Everybody the Planning Phase put in front of the Medical Clinic (pg. 21). */
export function beingHealed(campaign: Campaign): readonly Survivor[] {
  return survivorsDoing(campaign, (assignment) => assignment.task === 'healing');
}

/** Whoever is resting, and takes a point nobody else can use (pg. 21). */
export function resting(campaign: Campaign): readonly Survivor[] {
  return survivorsDoing(campaign, (assignment) => assignment.task === 'rest');
}

/**
 * A pool shared out one point at a time, in roster order.
 *
 * The loop terminates because `left` starts capped at the room available: while
 * a point is left there is somebody with room to take it, so every pass hands
 * out at least one. Capping up front is also the rule about surplus — a pool
 * bigger than the community can absorb leaves the rest unspent rather than
 * overhealing anybody.
 */
export function sharedEqually(
  survivors: readonly Survivor[],
  pool: number,
): readonly HealthAward[] {
  const filling = survivors.map((survivor) => ({ survivor, health: 0 }));
  const space = filling.reduce((total, each) => total + room(each.survivor), 0);

  let left = Math.min(pool, space);

  while (left > 0) {
    for (const each of filling) {
      if (left === 0) break;
      if (each.health >= room(each.survivor)) continue;

      each.health += 1;
      left -= 1;
    }
  }

  return filling
    .filter((each) => each.health > 0)
    .map((each) => ({ survivor: each.survivor.id, health: each.health, source: 'facility' }));
}

/**
 * Everything this turn's Heal Wounds step hands out.
 *
 * The shared pool and the resting survivors' own points together, because they
 * land on the same step and a screen that showed one without the other would be
 * telling half the turn.
 */
export function healthAwards(campaign: Campaign): readonly HealthAward[] {
  const shared = sharedEqually(beingHealed(campaign), healingPool(campaign));

  const rested = resting(campaign)
    .map((survivor) => ({
      survivor: survivor.id,
      health: Math.min(REST_HEALTH, room(survivor)),
      source: 'rest' as const,
    }))
    .filter((award) => award.health > 0);

  return [...shared, ...rested];
}

/**
 * How much of the pool nobody could take.
 *
 * Not an error and not a warning on its own — a Clinic that makes more than the
 * wounded can absorb is a community doing well. It is reported because it is
 * the number a player would otherwise spend a minute looking for.
 */
export function goingSpare(campaign: Campaign): number {
  const pool = healingPool(campaign);
  const taken = sharedEqually(beingHealed(campaign), pool).reduce(
    (total, award) => total + award.health,
    0,
  );

  return pool - taken;
}

/** What is worth saying about this turn's healing. Never a blocker. */
export function checkHealing(campaign: Campaign): HealingCheck {
  const warnings: HealingViolation[] = [];
  const spare = goingSpare(campaign);

  if (spare > 0 && beingHealed(campaign).length === 0) {
    warnings.push({
      code: 'nothing-to-share',
      message: `${spare} Health with nobody assigned to healing — it is lost at the end of the turn.`,
      pages: 21,
    });
  } else if (spare > 0) {
    warnings.push({
      code: 'health-going-spare',
      message: `${spare} Health more than the wounded can take. The surplus is not stored.`,
      pages: 19,
    });
  }

  return { blockers: [], warnings };
}

/**
 * Whether this turn's wounds have already been healed.
 *
 * Read off the log, like `planningHasBegun` and `materialsAdded`: the step
 * raises Health, the walk can go back over it, and doing it twice would heal a
 * community twice on one Clinic.
 */
export function woundsHealed(campaign: Campaign): boolean {
  return campaign.log.some(
    (entry) => entry.turn === campaign.turn && entry.event.kind === 'health-restored',
  );
}

/** The campaign with a turn's awards applied to the survivors who earned them. */
export function withWoundsHealed(campaign: Campaign, awards: readonly HealthAward[]): Campaign {
  return {
    ...campaign,
    survivors: campaign.survivors.map((survivor) => {
      const health = awards
        .filter((award) => award.survivor === survivor.id)
        .reduce((total, award) => total + award.health, 0);

      return { ...survivor, currentHp: survivor.currentHp + health };
    }),
  };
}
