/**
 * Heal Wounds — the fourth step of the Advancement Phase (pg. 19).
 *
 * ## Equally, which is an algorithm rather than a division
 *
 * A facility's Health points are shared **equally** among the survivors
 * assigned to healing: nobody takes a second point until everyone who can use
 * one has had a first. Dividing the pool by the head count gets this wrong the
 * moment anybody fills up — max HP is the survivor's Tier, and a survivor who
 * reaches it drops out and leaves the remainder to the others.
 *
 * So `sharedEqually` hands out one point at a time, in roster order, round
 * after round. Two things follow, and both are asserted as properties rather
 * than as examples: nobody ever exceeds their maximum, and between any two
 * survivors who are still taking points the allocations differ by at most one.
 *
 * ## Points first, Health second
 *
 * `sharedEqually` decides **who gets how many points**; `withWoundsHealed`
 * turns points into Health. They are two functions because the book will later
 * make them two decisions: a point spent on Infection instead of on a wound is
 * Phase 7 (pg. 30), and it is the same point from the same pool. Fusing the
 * distribution into the healing would mean taking them apart again.
 *
 * ## Rest is a different rule arriving at the same survivors
 *
 * A resting survivor generates one Health that **only they** may use (pg. 19,
 * 21). It never enters the shared pool, which is why it is a second function
 * rather than a survivor added to the first.
 *
 * Pure, like the rest of `src/engine`.
 */

import { REST_HEALTH, SURVIVORS_RESTING_PER_TURN, type HealthSource } from '../data/turn';
import { beforePlanning, staffOf, survivorsDoing } from './assignments';
import { suppliedOccupants } from './utilities';
import type { Campaign, Survivor } from './campaign';
import type { Check, Violation } from './checks';
import { facilityProduction } from './production';
import { hungerPenalty } from './feeding';
import { maxHp } from './survivor';

export type HealingViolationCode =
  'health-going-spare' | 'nothing-to-share' | 'more-than-one-resting';

export type HealingViolation = Violation<HealingViolationCode>;

export type HealingCheck = Check<HealingViolationCode>;

/**
 * One survivor's share of a turn's Health, and where it came from.
 *
 * Carries the survivor rather than their id. Every award is built *from* the
 * roster, so handing back an id would make every caller look up something it
 * was already holding — and the log needs the name as well as the id, which
 * would have put a second lookup in the reducer with a guard nothing could
 * reach. Safe to hold a snapshot because an award is never stored: it is
 * computed, applied, and gone.
 */
export interface HealthAward {
  readonly survivor: Survivor;
  readonly health: number;
  /** Shared out of a facility's pool, or generated by resting (pg. 19, 21). */
  readonly source: HealthSource;
}

/**
 * How much Health this survivor can still take.
 *
 * Never negative. A survivor above their maximum is a state the app can hold —
 * Health is typed in, and Z1-7's override lets a roster break the rules on
 * purpose — and "minus two rooms" is not a number any distribution should try
 * to reason about. No room is the honest answer.
 */
export function room(survivor: Survivor): number {
  return Math.max(0, maxHp(survivor) - survivor.currentHp);
}

/**
 * The Health the base's facilities make this turn (pg. 19, 69).
 *
 * Through `facilityProduction` and `staffOf`, so this and the number on the
 * slot card are the same computation summed differently — a Medical Clinic's
 * output is its staff's combined Medicine Score, halved for want of Water.
 */
export function healingPool(campaign: Campaign): number {
  // No base-less guard: `suppliedOccupants` returns nothing to loop over, which
  // is the same zero.
  const penalty = hungerPenalty(campaign);
  let total = 0;

  // Staffed last Planning Phase, read this Advancement one — so it is asked of
  // the campaign as it stood before this turn's Planning cleared the answer.
  const staffed = beforePlanning(campaign);

  for (const occupant of suppliedOccupants(staffed)) {
    for (const line of facilityProduction(occupant, staffOf(staffed, occupant.slotId), penalty)) {
      if (line.outputs.includes('health')) total += line.amount;
    }
  }

  return total;
}

/**
 * Everybody the *previous* Planning Phase put in front of the Medical Clinic
 * (pg. 21).
 *
 * Previous, and `beforePlanning` is what makes that word true once this turn's
 * Planning Phase has been entered. The two survivors this step owes a point to
 * were assigned a turn ago, and the assignment is gone by the time a player
 * steps back into Heal Wounds from Planning — which is exactly how two people
 * lost the Health the rules owed them and then faced a Rot check at 0 (issue
 * #95).
 */
export function beingHealed(campaign: Campaign): readonly Survivor[] {
  return survivorsDoing(beforePlanning(campaign), (assignment) => assignment.task === 'healing');
}

/** Whoever is resting, and takes a point nobody else can use (pg. 21). */
export function resting(campaign: Campaign): readonly Survivor[] {
  return survivorsDoing(beforePlanning(campaign), (assignment) => assignment.task === 'rest');
}

/**
 * A pool shared out one point at a time, in roster order.
 *
 * **Rounds rather than a while-loop.** Each round offers every survivor one
 * point, and nobody can need more rounds than the deepest wound — so the
 * bound comes from the rules rather than from a "did that pass hand anything
 * out" flag. An earlier draft used `while (left > 0)` and relied on the pool
 * being pre-capped to terminate, which was true and invisible: every mutant
 * that broke it hung the test runner instead of failing it, so eight of them
 * were "killed" by a twenty-second timeout apiece.
 *
 * The surplus rule falls out of the same bound. A pool bigger than the
 * community can absorb runs out of rounds with points still in it, and those
 * points are simply not handed out — nobody is overhealed.
 *
 * One mutant survives here and is equivalent: `round < rounds` swapped for
 * `round <= rounds` runs one extra pass, and by then everybody with room is
 * full, so the pass hands out nothing. A bound that is already sufficient
 * cannot be broken by making it larger.
 */
export function sharedEqually(
  survivors: readonly Survivor[],
  pool: number,
): readonly HealthAward[] {
  const filling = survivors.map((survivor) => ({ survivor, health: 0 }));
  const rounds = filling.reduce((deepest, each) => Math.max(deepest, room(each.survivor)), 0);

  let left = pool;

  for (let round = 0; round < rounds; round += 1) {
    for (const each of filling) {
      if (left <= 0) break;
      if (each.health >= room(each.survivor)) continue;

      each.health += 1;
      left -= 1;
    }
  }

  return filling
    .filter((each) => each.health > 0)
    .map((each) => ({ survivor: each.survivor, health: each.health, source: 'facility' }));
}

/**
 * Everything this turn's Heal Wounds step hands out.
 *
 * The shared pool and the resting survivors' own points together, because they
 * land on the same step and a screen that showed one without the other would be
 * telling half the turn.
 */
export function healthAwards(campaign: Campaign): readonly HealthAward[] {
  const shared = sharedEqually(beingHealed(campaign), healingPool(campaign));

  const rested = resting(campaign)
    .map((survivor) => ({
      survivor,
      health: Math.min(REST_HEALTH, room(survivor)),
      source: 'rest' as const,
    }))
    .filter((award) => award.health > 0);

  return [...shared, ...rested];
}

/**
 * How much of the pool nobody could take.
 *
 * Not an error and not a warning on its own — a Clinic that makes more than the
 * wounded can absorb is a community doing well. It is reported because it is
 * the number a player would otherwise spend a minute looking for.
 */
export function goingSpare(campaign: Campaign): number {
  const pool = healingPool(campaign);
  const taken = sharedEqually(beingHealed(campaign), pool).reduce(
    (total, award) => total + award.health,
    0,
  );

  return pool - taken;
}

/** What is worth saying about this turn's healing. Never a blocker. */
export function checkHealing(campaign: Campaign): HealingCheck {
  const warnings: HealingViolation[] = [];
  const spare = goingSpare(campaign);
  const resters = resting(campaign);

  /*
   * Only one survivor may rest a turn (pg. 21). The Planning Phase warns rather
   * than refuses, which is a deliberate ruling and not the problem — the
   * problem was that this step then paid *both* points out in silence, a phase
   * and four steps later, where nobody was looking at the warning any more. A
   * rule broken on purpose should still say so at the moment it costs
   * something.
   */
  if (resters.length > SURVIVORS_RESTING_PER_TURN) {
    warnings.push({
      code: 'more-than-one-resting',
      message: `${resters.length} survivors are resting, and each is taking a point. The book allows ${SURVIVORS_RESTING_PER_TURN} a turn.`,
      pages: 21,
    });
  }

  if (spare > 0 && beingHealed(campaign).length === 0) {
    warnings.push({
      code: 'nothing-to-share',
      message: `${spare} Health with nobody assigned to healing — it is lost at the end of the turn.`,
      pages: 21,
    });
  } else if (spare > 0) {
    warnings.push({
      code: 'health-going-spare',
      message: `${spare} Health more than the wounded can take. The surplus is not stored.`,
      pages: 19,
    });
  }

  return { blockers: [], warnings };
}

/**
 * Whether this turn's wounds have already been healed.
 *
 * Read off the log, like `planningHasBegun` and `materialsAdded`: the step
 * raises Health, the walk can go back over it, and doing it twice would heal a
 * community twice on one Clinic.
 */
export function woundsHealed(campaign: Campaign): boolean {
  return campaign.log.some(
    (entry) => entry.turn === campaign.turn && entry.event.kind === 'health-restored',
  );
}

/** The campaign with a turn's awards applied to the survivors who earned them. */
export function withWoundsHealed(campaign: Campaign, awards: readonly HealthAward[]): Campaign {
  return {
    ...campaign,
    survivors: campaign.survivors.map((survivor) => {
      const health = awards
        .filter((award) => award.survivor.id === survivor.id)
        .reduce((total, award) => total + award.health, 0);

      return { ...survivor, currentHp: survivor.currentHp + health };
    }),
  };
}
